
#Default column names

DEFAULT_USERID_COL = "user_id"
DEFAULT_LOCALE_COL = "locale"
DEFAULT_BIRTHYEAR_COL = "birthyear"
DEFAULT_GENDER_COL = "gender"
DEFAULT_JOINEDAT_COL = "joinedAt"
DEFAULT_LOCATION_COL = "location"
DEFAULT_TIMEZONE_COL = "timezone"
DEFAULT_USER_COL = "user"
DEFAULT_EVENT_COL = "event"
DEFAULT_INVITED_COL = "invited"
DEFAULT_TIMESTAMP_COL = "timestamp"
DEFAULT_INTERESTED_COL = "interested"
DEFAULT_NOT_INTERESTED_COL = "not_interested"
DEFAULT_FRIENDS_COL = "friends"




DEFAULT_USER_DF= {
    DEFAULT_USERID_COL,
    DEFAULT_LOCALE_COL,
    DEFAULT_BIRTHYEAR_COL, 
    DEFAULT_GENDER_COL,
    DEFAULT_JOINEDAT_COL, 
    DEFAULT_LOCATION_COL, 
    DEFAULT_TIMEZONE_COL, 

}

DEFAULT_TRAIN_DF={
    DEFAULT_USER_COL,
    DEFAULT_EVENT_COL,
    DEFAULT_INVITED_COL,
    DEFAULT_TIMESTAMP_COL,
    DEFAULT_INTERESTED_COL,
    DEFAULT_NOT_INTERESTED_COL

}


DEFAULT_FRIENDS_DF={
    DEFAULT_USER_COL,
    DEFAULT_FRIENDS_COL
}




