name: Test data

on:
  commit:
    # Only trigger the workflow with a commit to main
    branches:
    - dev
  pull_request:
    # Only trigger the workflow with a PR to main
    branches:
    - main

  # Enable manual trigger
  workflow_dispatch:
    input:
      tags:
        description: 'Tags to label this manual run (optional)'
        default: 'Manual run'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Test with pytest
      env:
      #DRIVE_API: ${{ secrets.DRIVE_API_CREDENTIALS }}
      DRIVE_API: "AIzaSyBdwGSwa_64SYxbOIgSkVflc3wz8ljU248"
      run: |
        cd tests
        python -m pytest